// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC35Ykl-b2ctxpWxRQtPuUpzI4xVG35R5o',
    appId: '1:897664205499:web:4074d1b28f156cd52fdf9e',
    messagingSenderId: '897664205499',
    projectId: 'chat-app-5cc4d',
    authDomain: 'chat-app-5cc4d.firebaseapp.com',
    storageBucket: 'chat-app-5cc4d.firebasestorage.app',
    measurementId: 'G-TY0PWRP7W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD44pxVHNIikrHlMRorcfggaPKn4QnZXLM',
    appId: '1:897664205499:android:0d0802df74aeeee32fdf9e',
    messagingSenderId: '897664205499',
    projectId: 'chat-app-5cc4d',
    storageBucket: 'chat-app-5cc4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmz20PKDsIUcx63C65COWEELEu2JPGNzg',
    appId: '1:897664205499:ios:2548721150a177f82fdf9e',
    messagingSenderId: '897664205499',
    projectId: 'chat-app-5cc4d',
    storageBucket: 'chat-app-5cc4d.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmz20PKDsIUcx63C65COWEELEu2JPGNzg',
    appId: '1:897664205499:ios:2548721150a177f82fdf9e',
    messagingSenderId: '897664205499',
    projectId: 'chat-app-5cc4d',
    storageBucket: 'chat-app-5cc4d.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC35Ykl-b2ctxpWxRQtPuUpzI4xVG35R5o',
    appId: '1:897664205499:web:8db2d210974696c42fdf9e',
    messagingSenderId: '897664205499',
    projectId: 'chat-app-5cc4d',
    authDomain: 'chat-app-5cc4d.firebaseapp.com',
    storageBucket: 'chat-app-5cc4d.firebasestorage.app',
    measurementId: 'G-NL16WVGK9E',
  );
}
